_target_: src.models.cnn.CNN

dataset_path : /root/workspace/lightning-hydra-template/data/ansim
cv_fold_idx: 1

hparams : 
  name: 'CNN'
  max_num_sources: 4
  sequence_duration: 30
  num_fft_bins: 2048
  frame_length: 0.04
  chunk_length: 0.5
  dropout_rate: 0
  learning_rate: 0.05
  num_epochs_warmup: 1
  gradient_clip_val: 1.0
  alpha: 1

# optimizer:
#   _target_: torch.optim.AdamW
#   _partial_: true
#   lr: 0.05
#   weight_decay: 0.0

# scheduler:
#   _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
#   _partial_: true
#   mode: min
#   factor: 0.1
#   patience: 10

# net:
#   _target_: src.models.components.simple_dense_net.SimpleDenseNet
#   input_size: 784
#   lin1_size: 64
#   lin2_size: 128
#   lin3_size: 64
#   output_size: 10

# # Model parameters
# name: 'CNN'
# max_num_sources: 4
# sequence_duration: 30
# num_fft_bins: 2048
# frame_length: 0.04
# chunk_length: 0.5
# dropout_rate: 0
# learning_rate: 0.05
# num_epochs_warmup: 1
# gradient_clip_val: 1.0
# alpha: 1

# # Experimental setup
# dataset: ['ansim']
# max_epochs: 100

# manual_seed: 1234
