_target_: src.models.cnn.CNN

dataset_path : /root/workspace/lightning-hydra-template/data/ansim
cv_fold_idx: 1

hparams : 
  name: 'CNN' # Name of the model
  max_num_sources: 3 # Maximum number of sources (related the output shape).
  sequence_duration: 30 # Assumed duration (s) of the audio samples (if not, cropping or padding performed).
  num_fft_bins: 2048 # Number of frequencies in STFT computation.
  frame_length: 0.04 # Length (s) of the analysis window (Default to hann) used for FFT computation.
  chunk_length: 0.5 # Duration (s) of the non-overlapping "chunks".
  dropout_rate: 0 # Dropout rate. 
  learning_rate: 0.05 # Initial learning rate to use in the optimization process. 
  num_epochs_warmup: 1 #Number of epochs from which the learning rate decay is enabled (see configure_optimizers in the AbstractLocalizationModule).
  alpha: 1 # Load of the direction_of_arrival_loss along with the source_activity_loss in the SEL (Sound Event Localization) Loss. 
  results_dir: /root/workspace/lightning-hydra-template/results # Result directory with json files, additionnaly to the eval directory in the logs generated. 
  # tmp_dir: ${paths.output_dir}/tmp