_target_: src.models.cnn.CNN

dataset_path : /root/workspace/lightning-hydra-template/data/ansim
cv_fold_idx: 1

hparams : 
  name: 'CNN'
  max_num_sources: 4
  sequence_duration: 30
  num_fft_bins: 2048
  frame_length: 0.04
  chunk_length: 0.5
  dropout_rate: 0
  learning_rate: 0.05
  num_epochs_warmup: 1
  gradient_clip_val: 1.0
  alpha: 1
  results_dir: /root/workspace/lightning-hydra-template/results