_target_: src.models.pilot.PILOT

dataset_path : /root/workspace/lightning-hydra-template/data/ansim
cv_fold_idx: 1

hparams : 
  name: 'PILOT'
  chunk_length: 0.5
  frame_length: 0.04
  num_fft_bins: 2048
  embedding_dim: 32
  feature_extraction_dropout: 0.
  transformer_num_heads: 8
  transformer_num_layers: 3
  transformer_feedforward_dim: 1024
  transformer_dropout: 0.1
  learning_rate: 0.05
  num_epochs_warmup: 5
  #Added
  max_num_sources: 1
  sequence_duration: 30
  gradient_clip_val: 1.0
  alpha: 1
  results_dir: /root/workspace/lightning-hydra-template/results

  # max_num_sources: 4
  # sequence_duration: 30
  # num_fft_bins: 2048
  # frame_length: 0.04
  # chunk_length: 0.5
  # dropout_rate: 0
  # learning_rate: 0.05
  # num_epochs_warmup: 1
  # gradient_clip_val: 1.0
  # alpha: 1
  # results_dir: /root/workspace/lightning-hydra-template/results




