# @package _global_

defaults:
  - _self_
  - data: ansim.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: pilot.yaml
  - logger: tensorboard
  - trainer: setup.yaml
  - paths: default.yaml
  - extras: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: /root/workspace/lightning-hydra-template/logs/old-trainings/runs/2023-03-03_20-15-11-Pilot_tt/checkpoints/epoch_009.ckpt
